services:
  api:
    build: .
    env_file:
      - variables.env
    ports:
      - "6001-6002:5001-5002"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file:
      - variables.env
volumes:
  database-data: